repositories:
    - name: dts
      url: https://helm.dts-stn.com
    # helm-git powered repository: You can treat any Git repository as a charts repository
    - name: dtspoc
      url: git+https://{{ requiredEnv "GITHUB_USER" }}:{{ requiredEnv "GITHUB_TOKEN" }}@github.com/DTS-STN/poc-intake@helm/charts?ref=helmfile
{{- if or (eq .Environment.Name "prod-blue") (eq .Environment.Name "prod-green") }}    
context: EsDCDTSRG-K8S
{{ else }}
context: EsDCDTSDevRG-K8S
{{ end }}
   
environments:
    benrd: 
    kylerd:
    adamrd:
    marcusrd:
    ericrd:
    dev:
    prod-blue:
    prod-green: 

releases:
  # poc-intake
  - name: poc-intake-{{ .Environment.Name }}
    chart: dtspoc/dts-poc-intake
    version: 1.0.0
    values:
      - overrides/gui.yaml.gotmpl
    labels:
        category: dts
        app: poc-intake
        tier: server
    namespace: poc-intake-{{ .Environment.Name }}
    installed: true
    wait: false

  # poc-intake-db
  - name: poc-intake-db-{{ .Environment.Name }}
    chart: bitnami/mongodb
    version: 7.0.0
    values:
      - overrides/dbvalues.yaml.gotmpl   
    labels:
        category: dts
        app: poc-intake
        tier: database
    namespace: poc-intake-{{ .Environment.Name }}
    installed: true
    wait: false
