version: '3.3'
services:

  poc-intake:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VUE_APP_CONNECTION_STRING: ${VUE_APP_CONNECTION_STRING}
        VUE_APP_POC_INTAKE_DB_PASSWORD: ${VUE_APP_POC_INTAKE_DB_PASSWORD}
    container_name: poc-intake
    restart: always
    ports:
     - "80:3000"

  e2e:
    build:
      context: ./
      dockerfile: Cypress.Dockerfile
    container_name: cypress
    depends_on:
      - poc-intake
    environment:
      - CYPRESS_baseUrl=http://localhost
    restart: always
    network_mode: 'host'
    volumes:
      - "./cypress/reports:/cypress/report"
