FROM node:11.15.0-alpine
WORKDIR /home/poc-intake
COPY package*.json ./
RUN npm install --production
COPY . .
RUN npm run build
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
ARG VUE_APP_CONNECTION_STRING=placeholder
ENV VUE_APP_CONNECTION_STRING=${VUE_APP_CONNECTION_STRING}
ARG VUE_APP_POC_INTAKE_DB_PASSWORD=placeholder
ENV VUE_APP_POC_INTAKE_DB_PASSWORD=${VUE_APP_POC_INTAKE_DB_PASSWORD}
ARG VUE_APP_API_URL=http://localhost:3000/api/
ENV VUE_APP_API_URL=${VUE_APP_API_URL}
EXPOSE ${NUXT_PORT}
CMD [ "npm", "start" ]
