FROM node:11.15.0-alpine
WORKDIR /.
COPY package*.json ./
RUN npm install --production
COPY . .
RUN npm run build
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
ARG CONNECTION_STRING=X
ENV CONNECTION_STRING=${CONNECTION_STRING}
ARG POC_INTAKE_DB_PASSWORD=X
ENV POC_INTAKE_DB_PASSWORD=${POC_INTAKE_DB_PASSWORD}
EXPOSE ${NUXT_PORT}
CMD [ "npm", "start" ]
